"""Phase 3 analysis: compute mini vs Sonnet agreement metrics on OH 300-slice.

See `docs/active/leave-behind-prep/plans/20260608_gpt5mini_on_oh_300slice.md`.

Reads:
  data/oh_portal/extracted/<report_id>/<sonnet_run>/filing.json     (Sonnet 1x)
  data/oh_portal/extracted_openai/<report_id>/mini_run_{1,2,3}_*/filing.json

Computes the three headline metrics from plan step 12:
  1. Mini self-consistency (sigma_noise): fraction of (filing, field_path)
     tuples where all 3 mini runs emit the same value. Aggregated overall
     and per field-type.
  2. Mini-vs-Sonnet per-run agreement: for each mini run separately, fraction
     of field-path tuples that match the Sonnet baseline. Three numbers.
  3. Stable-disagreement rate: fraction of field-paths where all 3 mini runs
     agree with each other AND disagree with Sonnet. Most informative single
     metric; surfaces 10-20 examples for hand-eyeballing.

Array alignment (concern #2 from the pre-dispatch review):
  The plan handles array-length mismatches as full-row disagreement but does
  not specify how to align same-length arrays. Naive index-zip inflates
  disagreement spuriously when two providers emit the same content in
  different orders.

  This script aligns rows by semantic key per array type:
    positions[]    by (bill_reference.original_text, description, position)
    expenditures[] by (category, recipient_name, amount, expenditure_date)
    engagements[]  by (contact_date, official_contacted, institution)
    gifts[]        by (gift_date, recipient_name, value)

  Rows that have a key in both files are compared field-by-field. Rows
  present only on one side count as full-row disagreement (every field-path
  of that row counts as one disagreement).

Outputs:
  results/20260608_gpt5mini_oh_300slice_metrics.json   raw metrics
  results/20260608_gpt5mini_oh_300slice_stable_disagreements.json  candidate
    list of stable-disagreement examples for hand-eyeballing (capped at
    --max-disagreement-examples, default 100; the plan's eyeball pass picks
    10-20 from these).

Cost projection (plan step 14):
  Reads usage data from each pass's extraction_run.json files, sums to a
  per-run cost, computes total + projection to 45,605 filings:
    projected_cost_full_corpus = total_cost_300slice * (45605 / 300)
  This is the number for Suhan's decisions doc.

Run: `python scripts/gpt5mini_oh_300slice_analyze.py`
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

# Resolve project paths and add src/ to sys.path.
_REPO_ROOT = Path(__file__).resolve().parents[1]
_SRC = _REPO_ROOT / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

# Pricing must match the dispatcher's constants — they're declared in both
# places intentionally so a pricing drift surfaces as an import-time error
# rather than as silently divergent cost numbers between dispatch and analyze.
from scripts.gpt5mini_oh_300slice_dispatch import (  # noqa: E402
    COST_PER_MTOK_COMPLETION,
    COST_PER_MTOK_PROMPT,
    EXTRACTED_OPENAI_SUBDIR,
)

FULL_CORPUS_SIZE = 45_605  # OH AER universe per Sonnet 300-slice writeup
RUN_LABELS = ("mini_run_1", "mini_run_2", "mini_run_3")

# Fields stamped by the pipeline rather than extracted by the model. Excluded
# from the comparison so they don't trivially "disagree" between providers.
_NON_EXTRACTED_TOP_LEVEL = {"raw_text", "provenance", "id"}
# `id` is generated by the model but is a free-text identifier and won't
# match across providers; excluding it avoids dominating disagreement counts.

# Array alignment keys. Each tuple lists the field names whose joint value
# identifies a "logically same" row across providers.
#
# Design constraint: keys must use only IDENTITY fields, not MEASURED fields.
# If we keyed expenditures on `amount`, then a row where Sonnet=$100 and
# mini=$105 (the exact disagreement we want to catch) would split into two
# rows — one Sonnet-only, one mini-only — and every field of each row would
# count as a full-row disagreement (5x inflation). Same trap for gifts.value
# and positions.position.
#
# Trade-off: the alternative failure mode is two genuinely-different rows
# collapsing under the same identity key (e.g., two gifts to the same person
# on the same date with different amounts). For OH legislative AERs this
# pattern is rare per the brief (Section II.A-C itemized, one row per
# logical transaction); the measurement-collapse trap is the bigger risk.
_ARRAY_ALIGNMENT_KEYS: dict[str, tuple[str, ...]] = {
    "positions": ("bill_reference.original_text",),
    "expenditures": ("category", "recipient_name", "expenditure_date"),
    "engagements": ("contact_date", "official_contacted"),
    "gifts": ("gift_date", "recipient_name"),
}


# ---------------------------------------------------------------------------
# Filing discovery
# ---------------------------------------------------------------------------


def _latest_filing_json(
    report_dir: Path, run_label_prefix: str | None = None
) -> Path | None:
    if not report_dir.is_dir():
        return None
    runs = sorted(
        d for d in report_dir.iterdir()
        if d.is_dir() and (
            run_label_prefix is None or d.name.startswith(run_label_prefix)
        )
    )
    for run_dir in reversed(runs):
        candidate = run_dir / "filing.json"
        if candidate.exists():
            return candidate
    return None


def _latest_extraction_run_json(
    report_dir: Path, run_label_prefix: str
) -> Path | None:
    if not report_dir.is_dir():
        return None
    runs = sorted(
        d for d in report_dir.iterdir()
        if d.is_dir() and d.name.startswith(run_label_prefix)
    )
    for run_dir in reversed(runs):
        candidate = run_dir / "extraction_run.json"
        if candidate.exists():
            return candidate
    return None


def assemble_extraction_set(
    data_dir: Path,
) -> tuple[dict[str, dict], dict[str, list[dict]]]:
    """Build (sonnet, mini) maps from the on-disk extraction trees.

    Returns:
      sonnet: report_id -> filing dict (1x per report).
      mini:   report_id -> list of 3 filing dicts (one per run_label,
              ordered mini_run_1, mini_run_2, mini_run_3). Filings missing
              any of the 3 runs are excluded.
    """
    sonnet_dir = data_dir / "extracted"
    mini_dir = data_dir / EXTRACTED_OPENAI_SUBDIR

    sonnet: dict[str, dict] = {}
    if sonnet_dir.is_dir():
        for report_dir in sonnet_dir.iterdir():
            if not report_dir.is_dir():
                continue
            fj = _latest_filing_json(report_dir)
            if fj is None:
                continue
            sonnet[report_dir.name] = json.loads(fj.read_text())

    mini: dict[str, list[dict]] = {}
    if mini_dir.is_dir():
        for report_dir in mini_dir.iterdir():
            if not report_dir.is_dir():
                continue
            per_run: list[dict] = []
            ok = True
            for label in RUN_LABELS:
                fj = _latest_filing_json(report_dir, run_label_prefix=f"{label}_")
                if fj is None:
                    ok = False
                    break
                per_run.append(json.loads(fj.read_text()))
            if ok:
                mini[report_dir.name] = per_run

    return sonnet, mini


# ---------------------------------------------------------------------------
# Field-path enumeration with key-aligned arrays
# ---------------------------------------------------------------------------


def _path_value(obj: Any, dotted_path: str) -> Any:
    """Resolve a dotted path (e.g., "bill_reference.original_text") on a dict."""
    cur = obj
    for part in dotted_path.split("."):
        if cur is None:
            return None
        if not isinstance(cur, dict):
            return None
        cur = cur.get(part)
    return cur


def _row_key(row: dict, key_fields: tuple[str, ...]) -> tuple:
    """Tuple-of-strings key for aligning rows of an array across providers."""
    return tuple(
        "<null>" if (_path_value(row, f) is None) else str(_path_value(row, f))
        for f in key_fields
    )


def _flatten_top_level_scalars(filing: dict) -> dict[str, Any]:
    """Top-level fields that are NOT arrays/objects (basic scalars + simple maps)."""
    out: dict[str, Any] = {}
    for k, v in filing.items():
        if k in _NON_EXTRACTED_TOP_LEVEL:
            continue
        if isinstance(v, list):
            continue
        if k in ("filer_person", "filer_organization", "employer"):
            # Nested entity — flatten one level for comparison.
            if isinstance(v, dict):
                for sub_k, sub_v in v.items():
                    if sub_k in ("provenance", "id", "contact_details",
                                 "identifiers", "prior_public_offices",
                                 "name_components"):
                        continue
                    out[f"{k}.{sub_k}"] = sub_v
            else:
                out[k] = v
            continue
        out[k] = v
    return out


def _array_row_field_values(
    array_name: str, rows: list[dict] | None, key_fields: tuple[str, ...]
) -> dict[tuple, dict[str, Any]]:
    """Return {row_key: {field: value, ...}} for one filing's rows.

    `field` excludes per-row `provenance` (pipeline-stamped, not extracted).
    """
    if not rows:
        return {}
    out: dict[tuple, dict[str, Any]] = {}
    for row in rows:
        key = _row_key(row, key_fields)
        fields = {k: v for k, v in row.items() if k != "provenance"}
        # Multiple rows can share a key (e.g., two $50 entertainment expenses
        # to the same recipient on the same date). Differentiate by occurrence
        # index within the key group.
        occurrence = 0
        candidate_key = key
        while candidate_key in out:
            occurrence += 1
            candidate_key = key + (f"#{occurrence}",)
        out[candidate_key] = fields
    return out


# ---------------------------------------------------------------------------
# Pairwise comparison
# ---------------------------------------------------------------------------


def _values_equal(a: Any, b: Any) -> bool:
    """Equality for extracted values. Lists order-sensitive (top-level only)."""
    if a is None and b is None:
        return True
    if a is None or b is None:
        return False
    if isinstance(a, float) or isinstance(b, float):
        try:
            return float(a) == float(b)
        except (TypeError, ValueError):
            return False
    return a == b


def _compare_top_level(filings: list[dict]) -> dict[str, list[Any]]:
    """For each top-level scalar field, return the per-filing values list."""
    if not filings:
        return {}
    flat = [_flatten_top_level_scalars(f) for f in filings]
    keys = set().union(*(d.keys() for d in flat))
    return {k: [d.get(k) for d in flat] for k in sorted(keys)}


def _compare_arrays(
    array_name: str, filings: list[dict]
) -> tuple[dict[str, list[list[Any]]], int, int]:
    """Per-array-row-field comparison.

    Returns:
      field_values: {f"{array_name}[{key}].{field}": [v_filing0, v_filing1, ...]}
        with None for filings lacking that key.
      n_rows_present_in_all: rows where the key exists in every filing.
      n_rows_present_in_some: rows where the key exists in at least one.
    """
    key_fields = _ARRAY_ALIGNMENT_KEYS[array_name]
    per_filing_rows = [
        _array_row_field_values(array_name, f.get(array_name), key_fields)
        for f in filings
    ]
    all_keys: set[tuple] = set()
    for d in per_filing_rows:
        all_keys.update(d.keys())

    field_values: dict[str, list[list[Any]]] = {}
    n_in_all = 0
    n_in_some = len(all_keys)

    for key in sorted(all_keys, key=str):
        present_everywhere = all(key in d for d in per_filing_rows)
        if present_everywhere:
            n_in_all += 1
        row_dicts = [d.get(key, {}) for d in per_filing_rows]
        all_fields: set[str] = set()
        for rd in row_dicts:
            all_fields.update(rd.keys())
        for f in sorted(all_fields):
            path = f"{array_name}[{'|'.join(key)}].{f}"
            field_values[path] = [
                rd.get(f) if rd else None for rd in row_dicts
            ]
        # If a row is missing entirely from one filing, count the missing
        # row's "expected" fields as None — already done above by rd being {}.

    return field_values, n_in_all, n_in_some


def per_filing_field_comparison(
    sonnet_filing: dict, mini_filings: list[dict]
) -> dict[str, list[Any]]:
    """All field-path comparisons for one report_id.

    Returns {field_path: [sonnet_value, mini_run_1, mini_run_2, mini_run_3]}.
    """
    filings = [sonnet_filing] + mini_filings
    all_paths: dict[str, list[Any]] = {}
    # Top-level scalars.
    all_paths.update(_compare_top_level(filings))
    # Arrays, key-aligned.
    for array_name in _ARRAY_ALIGNMENT_KEYS:
        arr_paths, _, _ = _compare_arrays(array_name, filings)
        all_paths.update(arr_paths)
    return all_paths


# ---------------------------------------------------------------------------
# Metric aggregation
# ---------------------------------------------------------------------------


def classify_path(
    sonnet_v: Any, mini_vs: list[Any]
) -> dict[str, bool]:
    """Classify one (filing, field_path) tuple into the metric buckets.

    Returns:
      mini_self_consistent: all 3 mini values equal.
      mini_run_i_matches_sonnet (i=1,2,3): per-run agreement with Sonnet.
      stable_disagreement: mini self-consistent AND mini != sonnet.
    """
    m1, m2, m3 = mini_vs
    self_consistent = _values_equal(m1, m2) and _values_equal(m2, m3)
    matches = [_values_equal(mini_vs[i], sonnet_v) for i in range(3)]
    stable_disagreement = self_consistent and not matches[0]
    return {
        "mini_self_consistent": self_consistent,
        "mini_run_1_matches_sonnet": matches[0],
        "mini_run_2_matches_sonnet": matches[1],
        "mini_run_3_matches_sonnet": matches[2],
        "stable_disagreement": stable_disagreement,
    }


def aggregate_metrics(
    sonnet: dict[str, dict], mini: dict[str, list[dict]]
) -> dict[str, Any]:
    """Compute the three headline metrics across all comparable report_ids."""
    common = sorted(set(sonnet) & set(mini))
    counters: Counter = Counter()
    field_type_counters: dict[str, Counter] = defaultdict(Counter)
    stable_disagreements: list[dict] = []
    n_paths_total = 0

    for report_id in common:
        comp = per_filing_field_comparison(sonnet[report_id], mini[report_id])
        for path, values in comp.items():
            sonnet_v, *mini_vs = values
            cls = classify_path(sonnet_v, mini_vs)
            counters["paths"] += 1
            n_paths_total += 1
            # Field-type bucket: top-level scalar or "<array_name>.field".
            if "[" in path:
                field_type = path.split("[", 1)[0] + ".*." + path.split("].", 1)[1]
            else:
                field_type = path
            for k, v in cls.items():
                if v:
                    counters[k] += 1
                    field_type_counters[field_type][k] += 1
            field_type_counters[field_type]["paths"] += 1
            if cls["stable_disagreement"]:
                stable_disagreements.append({
                    "report_id": report_id,
                    "field_path": path,
                    "sonnet_value": sonnet_v,
                    "mini_values": mini_vs,
                })

    def _rate(num: int, denom: int) -> float:
        return round(num / denom, 4) if denom else 0.0

    n = counters["paths"]
    headline = {
        "n_report_ids_compared": len(common),
        "n_field_paths_compared": n,
        "mini_sigma_noise": _rate(counters["mini_self_consistent"], n),
        "mini_run_1_vs_sonnet_agreement": _rate(
            counters["mini_run_1_matches_sonnet"], n
        ),
        "mini_run_2_vs_sonnet_agreement": _rate(
            counters["mini_run_2_matches_sonnet"], n
        ),
        "mini_run_3_vs_sonnet_agreement": _rate(
            counters["mini_run_3_matches_sonnet"], n
        ),
        "stable_disagreement_rate": _rate(counters["stable_disagreement"], n),
    }
    # Per-field-type breakdown (helps interpret aggregate numbers — high
    # disagreement on free-text fields with high agreement on numerics
    # tells a different story than uniform mediocrity).
    by_field_type = {}
    for ft, c in sorted(field_type_counters.items()):
        npaths = c["paths"]
        by_field_type[ft] = {
            "n_paths": npaths,
            "mini_sigma_noise": _rate(c["mini_self_consistent"], npaths),
            "stable_disagreement_rate": _rate(c["stable_disagreement"], npaths),
        }

    return {
        "headline": headline,
        "by_field_type": by_field_type,
        "stable_disagreements": stable_disagreements,
    }


# ---------------------------------------------------------------------------
# Cost + wall-clock from on-disk extraction_run.json
# ---------------------------------------------------------------------------


def aggregate_cost_and_wall(
    mini_report_ids: list[str], data_dir: Path
) -> dict[str, Any]:
    mini_dir = data_dir / EXTRACTED_OPENAI_SUBDIR
    per_run: dict[str, dict] = {
        label: {
            "prompt_tokens": 0, "completion_tokens": 0,
            "wall_clock_s": 0.0, "n_filings": 0,
        }
        for label in RUN_LABELS
    }
    for report_id in mini_report_ids:
        report_dir = mini_dir / report_id
        for label in RUN_LABELS:
            run_meta_path = _latest_extraction_run_json(report_dir, f"{label}_")
            if run_meta_path is None:
                continue
            meta = json.loads(run_meta_path.read_text())
            usage = meta.get("usage") or {}
            per_run[label]["prompt_tokens"] += usage.get("prompt_tokens", 0)
            per_run[label]["completion_tokens"] += usage.get("completion_tokens", 0)
            per_run[label]["wall_clock_s"] += meta.get("duration_seconds", 0.0)
            per_run[label]["n_filings"] += 1
    totals = {"prompt_tokens": 0, "completion_tokens": 0, "wall_clock_s": 0.0}
    for label, d in per_run.items():
        cost = (
            d["prompt_tokens"] / 1_000_000 * COST_PER_MTOK_PROMPT
            + d["completion_tokens"] / 1_000_000 * COST_PER_MTOK_COMPLETION
        )
        d["cost_usd"] = round(cost, 4)
        totals["prompt_tokens"] += d["prompt_tokens"]
        totals["completion_tokens"] += d["completion_tokens"]
        totals["wall_clock_s"] += d["wall_clock_s"]
    total_cost = (
        totals["prompt_tokens"] / 1_000_000 * COST_PER_MTOK_PROMPT
        + totals["completion_tokens"] / 1_000_000 * COST_PER_MTOK_COMPLETION
    )
    totals["cost_usd"] = round(total_cost, 4)
    totals["wall_clock_s"] = round(totals["wall_clock_s"], 1)

    n_slice = len(mini_report_ids)
    projected_full_corpus = (
        total_cost * (FULL_CORPUS_SIZE / n_slice) if n_slice else None
    )

    return {
        "per_run": per_run,
        "totals": totals,
        "projected_full_corpus_cost_usd": (
            round(projected_full_corpus, 2)
            if projected_full_corpus is not None else None
        ),
        "full_corpus_size": FULL_CORPUS_SIZE,
        "n_slice_filings": n_slice,
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--data-dir",
        default=str(Path(__file__).resolve().parents[1] / "data" / "oh_portal"),
        help="OH portal data directory.",
    )
    parser.add_argument(
        "--results-dir",
        default=str(
            Path(__file__).resolve().parents[1]
            / "docs" / "active" / "leave-behind-prep" / "results"
        ),
        help="Directory to write the metrics + disagreement JSON.",
    )
    parser.add_argument(
        "--max-disagreement-examples", type=int, default=100,
        help="Cap on stable-disagreement examples emitted for eyeballing.",
    )
    args = parser.parse_args()

    data_dir = Path(args.data_dir)
    results_dir = Path(args.results_dir)
    results_dir.mkdir(parents=True, exist_ok=True)

    sonnet, mini = assemble_extraction_set(data_dir)
    print(
        f"[analyze] {len(sonnet)} sonnet filings, "
        f"{len(mini)} mini filings (with all 3 runs)",
        file=sys.stderr,
    )

    common = sorted(set(sonnet) & set(mini))
    if not common:
        print(
            "[analyze] No report_ids have both Sonnet and 3-run mini outputs. "
            "Dispatch may not have completed; check extracted_openai/.",
            file=sys.stderr,
        )
        return 2

    metrics = aggregate_metrics(sonnet, mini)
    costs = aggregate_cost_and_wall(common, data_dir)

    metrics_out = {
        "headline": metrics["headline"],
        "by_field_type": metrics["by_field_type"],
        "cost_and_wall_clock": costs,
    }
    metrics_path = results_dir / "20260608_gpt5mini_oh_300slice_metrics.json"
    metrics_path.write_text(json.dumps(metrics_out, indent=2))
    print(f"[analyze] metrics -> {metrics_path}", file=sys.stderr)

    disagreements = metrics["stable_disagreements"]
    # Cap and shuffle would lose ordering; instead cap deterministically by
    # taking every Nth element to surface a spread of report_ids rather than
    # 100 from the first 5 reports.
    if len(disagreements) > args.max_disagreement_examples:
        step = max(1, len(disagreements) // args.max_disagreement_examples)
        disagreements = disagreements[::step][: args.max_disagreement_examples]
    disagree_path = (
        results_dir / "20260608_gpt5mini_oh_300slice_stable_disagreements.json"
    )
    disagree_path.write_text(json.dumps({
        "n_total_stable_disagreements": metrics["headline"][
            "stable_disagreement_rate"
        ] * metrics["headline"]["n_field_paths_compared"],
        "n_emitted": len(disagreements),
        "examples": disagreements,
    }, indent=2, default=str))
    print(f"[analyze] stable disagreements -> {disagree_path}", file=sys.stderr)

    print("\n========== HEADLINE ==========", file=sys.stderr)
    print(json.dumps(metrics["headline"], indent=2), file=sys.stderr)
    print("\n========== COST + WALL CLOCK ==========", file=sys.stderr)
    print(json.dumps(costs, indent=2), file=sys.stderr)

    # Pre-registered verdict from plan step 14.
    h = metrics["headline"]
    sigma = h["mini_sigma_noise"]
    stable = h["stable_disagreement_rate"]
    if sigma > 0.90 and stable < 0.10:
        verdict = (
            "plausibly viable, recommend follow-on hand-validation post-Fellowship"
        )
    elif sigma > 0.90 and stable < 0.25:
        verdict = (
            "viable on consistency, needs hand-judgment on disagreement "
            "category mix before commitment"
        )
    else:
        verdict = "not suitable at current setup; deeper investigation needed"
    print(f"\nPRE-REGISTERED VERDICT: {verdict}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
